### PR TITLE
Generate ISO Image

### PR DESCRIPTION
**Pull request by doztrock**
I've added the rules in the `Makefile` to generate an .iso file.

I've added some `.PHONY` lines to the folder `kernel/` and `iso/`.

I've added an exception to the `.gitignore` file to NetBeans project folder.

### CODE REVIEW

**Comment by ketanhwr** [comment]
Thanks! :slightly_smiling_face:

**Comment by doztrock** [comment]
@ketanhwr Will you start a libc? Can I make a proposal? I've a tiny libc I've used for my hobbie osdev project, maybe i could include, anyway what is next? :)

Regards

**Comment by ketanhwr** [comment]
I'll start soon I think, I'm yet to think up of a roadmap. Nevertheless, feel free to share your implementation, I can use it as a reference! :slightly_smiling_face:

**Comment by doztrock** [comment]
Perfect, i'll add a tiny implementation based on the directory structure

**Pull request merged**
